package kr.ssogari.smsextract

object PduHeaders {
    const val MESSAGE_TYPE_NOTIFICATION_IND = 130
    const val MESSAGE_TYPE_SEND_REQ = 128
    const val MESSAGE_TYPE_RETRIEVE_CONF = 132
    const val MESSAGE_TYPE_DELIVERY_IND = 134
    const val MESSAGE_TYPE_ACKNOWLEDGE_IND = 133
    const val MESSAGE_TYPE_READ_ORIG_IND = 136
    const val MESSAGE_TYPE_READ_REC_IND = 135
    const val MESSAGE_TYPE_MBOX_STORE_REQ = 145
    const val MESSAGE_TYPE_MBOX_STORE_CONF = 146
    const val MESSAGE_TYPE_MBOX_VIEW_REQ = 147
    const val MESSAGE_TYPE_MBOX_VIEW_CONF = 148
    const val MESSAGE_TYPE_MBOX_UPLOAD_REQ = 149
    const val MESSAGE_TYPE_MBOX_UPLOAD_CONF = 150
    const val MESSAGE_TYPE_MBOX_DELETE_REQ = 151
    const val MESSAGE_TYPE_MBOX_DELETE_CONF = 152
    const val MESSAGE_TYPE_DELETE_REQ = 153
    const val MESSAGE_TYPE_DELETE_CONF = 154
    const val MESSAGE_TYPE_CANCEL_REQ = 155
    const val MESSAGE_TYPE_CANCEL_CONF = 156
    const val MESSAGE_TYPE_REPLY_CHARGING_REQ = 157
    const val MESSAGE_TYPE_REPLY_CHARGING_CONF = 158
    const val MESSAGE_TYPE_REPLY_CHARGING_IND = 159
    const val MESSAGE_TYPE_REPLY_CHARGING_ACK = 160
    const val MESSAGE_TYPE_REPLY_CHARGING_NACK = 161
    const val MESSAGE_TYPE_FORWARD_REQ = 128
    const val MESSAGE_TYPE_FORWARD_CONF = 129
}
